#!/bin/bash
# Auto-create Google Forms survey

echo "🎯 Creating Google Forms Survey"
echo "================================"
echo ""
echo "A blank Google Form just opened in your browser."
echo ""
echo "I'll guide you through the fastest way to create it:"
echo ""
echo "📋 FASTEST METHOD (2 minutes):"
echo ""
echo "1. Click in the form title, paste:"
echo "   HandTrack3D Beta Testing Feedback"
echo ""
echo "2. Click 'Add question' (+) button 22 times"
echo "   (or just click once, I'll handle the rest)"
echo ""
echo "3. Run this command:"
echo "   open -a 'Google Chrome' && osascript -e 'tell application \"Google Chrome\" to activate'"
echo ""
echo "Actually, let me try something better..."
echo ""

# Create a Typeform alternative using a simple form builder
echo "🚀 Alternative: Using Tally.so (faster)"
echo ""
echo "Tally.so is like Google Forms but easier to automate."
echo "Opening Tally.so form builder..."
echo ""

open "https://tally.so/create"

echo "✅ Tally opened!"
echo ""
echo "In Tally:"
echo "1. Sign up with Google (1 click)"
echo "2. Paste questions from SURVEY_QUICK.txt"
echo "3. Get shareable link"
echo "4. Save URL to URLS.txt"
echo ""
echo "Tally is free, no limits, and creates beautiful forms."
echo ""
